dist: trusty

matrix:

    include:

        -
            language: node_js
            node_js: 8
            env:
                - NODE_ENV=development
            before_install:
                - cd client
            install:
                - yarn install
            script:
                - npm run lint
                - npm run build
                - npm run test
        -
            language: php
            php: 7.2
            services:
                - postgresql
            env:
                - APP_DEBUG=1
                - APP_ENV=test
                - APP_SECRET=s$cretf0rt3st
                - CORS_ALLOW_ORIGIN="^https?://localhost:?[0-9]*$"
                - DATABASE_URL=pgsql://postgres@localhost:5432/postgres
                - JWT_PRIVATE_KEY_PATH=config/jwt/private.pem
                - JWT_PUBLIC_KEY_PATH=config/jwt/public.pem
                - JWT_PASSPHRASE=6caf469adc8be6001f92c944681cc48c
            before_install:
                - cd server
            install:
                - composer install
            before_script:
                - bin/console doctrine:schema:create -vv --no-interaction
                - bin/console hautelook:fixtures:load -vv --no-interaction
                - bin/console cache:warmup
            script:
                - vendor/bin/phpunit

        -
            language: generic
            services:
                - docker
            env:
                - COMPOSE_FILE=docker-compose.yml.dist
            script:
                - docker-compose build
