security:

    access_control:
        - { path: ^/docs,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,       roles: IS_AUTHENTICATED_FULLY }

    encoders:
        App\Entity\User: bcrypt

    firewalls:
        login:
            pattern:  ^/login
            stateless: true
            guard:
                authenticators:
                    - App\Security\UserAuthenticator
        docs:
            pattern: ^/docs
            stateless: true
            anonymous: true

        api:
            pattern: ^/
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    providers:
        user:
            id: App\Security\UserProvider

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
